/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        'stancl.tenancy.asset': [
            {
                name: 'path';
                required: false;
            },
        ];
        'tenant.stancl.tenancy.asset': [
            {
                name: 'tenant';
                required: true;
            },
            {
                name: 'path';
                required: false;
            },
        ];
        home: [
            {
                name: 'locale';
                required: true;
            },
        ];
        dashboard: [
            {
                name: 'locale';
                required: true;
            },
        ];
        'profile.edit': [
            {
                name: 'locale';
                required: true;
            },
        ];
        'profile.update': [
            {
                name: 'locale';
                required: true;
            },
        ];
        'profile.destroy': [
            {
                name: 'locale';
                required: true;
            },
        ];
        'password.edit': [
            {
                name: 'locale';
                required: true;
            },
        ];
        'password.update': [
            {
                name: 'locale';
                required: true;
            },
        ];
        appearance: [
            {
                name: 'locale';
                required: true;
            },
        ];
        register: [
            {
                name: 'locale';
                required: true;
            },
        ];
        login: [
            {
                name: 'locale';
                required: true;
            },
        ];
        'login.store': [
            {
                name: 'locale';
                required: true;
            },
        ];
        'password.request': [
            {
                name: 'locale';
                required: true;
            },
        ];
        'password.email': [
            {
                name: 'locale';
                required: true;
            },
        ];
        'password.reset': [
            {
                name: 'locale';
                required: true;
            },
            {
                name: 'token';
                required: true;
            },
        ];
        'password.store': [
            {
                name: 'locale';
                required: true;
            },
        ];
        'verification.notice': [
            {
                name: 'locale';
                required: true;
            },
        ];
        'verification.verify': [
            {
                name: 'locale';
                required: true;
            },
            {
                name: 'id';
                required: true;
            },
            {
                name: 'hash';
                required: true;
            },
        ];
        'verification.send': [
            {
                name: 'locale';
                required: true;
            },
        ];
        'password.confirm': [
            {
                name: 'locale';
                required: true;
            },
        ];
        logout: [
            {
                name: 'locale';
                required: true;
            },
        ];
        'storage.local': [
            {
                name: 'path';
                required: true;
            },
        ];
        tenant: [];
    }
}
export {};
