// This file is automatically generated by i18next-cli, because it was not existing. You can edit it based on your needs: https://www.i18next.com/overview/typescript#custom-type-options
import type { defaultNS, resources } from '@/i18n';
// import type Resources from './resources';

declare module 'i18next' {
  interface CustomTypeOptions {
    enableSelector: true;
    defaultNS: typeof defaultNS;
    resources: typeof resources.en;
    // resources: Resources;
    strictKeyChecks: true;
  }
}
