export type TranslationKey =
  | ':selected of :total rows selected'
  | ':total rows'
  | 'A new verification link has been sent to your email address.'
  | 'A reset link will be sent if the account exists.'
  | 'Access your church data securely from anywhere, on any device, at any time.'
  | 'Account Number'
  | 'Accounting'
  | 'Actions'
  | 'Activate'
  | 'Active'
  | 'Add :model'
  | 'Address'
  | 'Address line 1'
  | 'Address line 2'
  | 'Admin'
  | 'Administration'
  | 'Amount'
  | 'Appearance'
  | 'Appearance Settings'
  | 'Appearance settings'
  | 'Are you sure you want to activate this :model?'
  | 'Are you sure you want to deactivate this :model?'
  | 'Are you sure you want to delete this :model?'
  | 'Arrastra y suelta tu foto aquí o haz <span class=\'filepond--label-action\'>clic</span> para seleccionarla'
  | 'Arrastra y suelta tus archivos o <span class=\'filepond--label-action\'>Buscar</span>'
  | 'Asc'
  | 'Assigned permissions'
  | 'Available funds'
  | 'Balance'
  | 'Bank Name'
  | 'Cancel'
  | 'Cash'
  | 'Categories'
  | 'Category'
  | 'Check'
  | 'Check layout'
  | 'Check layout is not available on mobile devices'
  | 'Checks'
  | 'Church'
  | 'Church Name'
  | 'Church Settings'
  | 'Church language'
  | 'ChurchesAdmin gave us peace of mind. Payroll is no longer a burden, and our team finally has time to focus on ministry.”'
  | 'ChurchesAdmin helps you manage your church with ease, while also keeping track of offerings, members and missionaries - all in one beautiful dashboard.'
  | 'ChurchesAdmin. All rights reserved.'
  | 'City'
  | 'Civil status'
  | 'Clergy Payroll Made Easy'
  | 'Click here to resend the verification email.'
  | 'Code'
  | 'Codes'
  | 'Columns'
  | 'Confirm password'
  | 'Confirmed'
  | 'Confirmed Checks'
  | 'Contact Information'
  | 'Contact us: :email | :phone'
  | 'Continue'
  | 'Country'
  | 'Create :model'
  | 'Create a new :model'
  | 'Create layout'
  | 'Current balance'
  | 'Current password'
  | 'Dashboard'
  | 'Date'
  | 'Date of Expense'
  | 'Date of Offering'
  | 'Deactivate'
  | 'Default amount'
  | 'Delete'
  | 'Delete :model'
  | 'Desc'
  | 'Description'
  | 'Deseleccionar'
  | 'Donor'
  | 'Edit'
  | 'Edit :model'
  | 'Edit the details of this :model'
  | 'Effortless Church'
  | 'Effortless Church Administration'
  | 'Email'
  | 'Email address'
  | 'Ensure your account is using a long, random password to stay secure'
  | 'Enter layout height'
  | 'Enter layout name'
  | 'Enter layout width'
  | 'Enter the value for this field'
  | 'Error submiting the form'
  | 'Every month'
  | 'Every six months'
  | 'Every three months'
  | 'Every two months'
  | 'Every two weeks'
  | 'Every week'
  | 'Every year'
  | 'Expense'
  | 'Expense Details'
  | 'Expense type'
  | 'Expense types'
  | 'Expenses'
  | 'Expenses total'
  | 'Five Hundred Forty-Nine and 00/100'
  | 'Force Delete Member'
  | 'Force Delete Missionary'
  | 'Foto de Perfil'
  | 'From'
  | 'Full name'
  | 'Gender'
  | 'General'
  | 'General information'
  | 'Global Access'
  | 'Go to the first page'
  | 'Go to the last page'
  | 'Go to the next page'
  | 'Go to the previous page'
  | 'Handle housing allowances, tax complexities, and direct deposits - all automated and accurate.'
  | 'Height'
  | 'Here you can update the printing check layout'
  | 'Inactive'
  | 'Initial Amount'
  | 'Initial check number'
  | 'Ir atrás'
  | 'Keep detailed records, contact info, and family ties for every member of your congregation.'
  | 'Language'
  | 'Last Name'
  | 'Last name'
  | 'Let us walk you through how ChurchesAdmin can serve your ministry\'s needs.'
  | 'Log Out'
  | 'Logo'
  | 'Main'
  | 'Manage :model'
  | 'Manage church information'
  | 'Manage your profile and account settings'
  | 'Mark this category as regular'
  | 'Mark this skill as regular'
  | 'Member'
  | 'Member Management'
  | 'Members'
  | 'Memo'
  | 'Missionaries'
  | 'Missionary'
  | 'Missionary Oversight'
  | 'Name'
  | 'Name of Payee'
  | 'New :model'
  | 'New password'
  | 'No Role'
  | 'No check layout selected for this wallet'
  | 'No data'
  | 'No options found'
  | 'No results'
  | 'No results found.'
  | 'Note'
  | 'Number'
  | 'Offering'
  | 'Offering Frequency'
  | 'Offering type'
  | 'Offering types'
  | 'Offerings'
  | 'One time only'
  | 'Only admins would be allowed to edit and delete this category'
  | 'Only admins would be allowed to edit and delete this skill'
  | 'Page :index of :total'
  | 'Password'
  | 'Password confirmation'
  | 'Password settings'
  | 'Pastor Maria, Lighthouse Church'
  | 'Payer'
  | 'Payment Method'
  | 'Payment method'
  | 'Phone'
  | 'Please use a desktop device to edit the check layout'
  | 'Preview'
  | 'Profile'
  | 'Profile Settings'
  | 'Profile information'
  | 'Ready to See ChurchesAdmin in Action?'
  | 'Regular tags'
  | 'Required fields'
  | 'Restore Member'
  | 'Restore Missionary'
  | 'Rev. Daniel, Hope Mission Center'
  | 'Role'
  | 'Roles'
  | 'Routing Number'
  | 'Rows per page'
  | 'Save'
  | 'Save password'
  | 'Saved'
  | 'Schedule a demo'
  | 'Search for a country...'
  | 'Secretary'
  | 'Select an option'
  | 'Select the layout you want to use for this wallet or create a new one'
  | 'Settings'
  | 'Skill'
  | 'Skills'
  | 'Social Media'
  | 'State'
  | 'Summary'
  | 'Super Admin'
  | 'Tags'
  | 'This action cannot be undone'
  | 'This action cannot be undone.'
  | 'This is how the information will look on the check layout'
  | 'This is marked as regular.'
  | 'This wallet will be usable again'
  | 'This wallet won\'t be usable until it is activated'
  | 'Total'
  | 'Track assignments, support levels, communication logs, and prayer requests with ease.'
  | 'Transactions'
  | 'Type'
  | 'Unconfirmed Checks'
  | 'Update :model'
  | 'Update account\'s appearance settings'
  | 'Update password'
  | 'Update the church information'
  | 'Update the website language'
  | 'Update your name and email address'
  | 'Upload the church logo'
  | 'Use this layout'
  | 'User'
  | 'Users'
  | 'Using the :name layout'
  | 'View'
  | 'Wallet'
  | 'Wallet :name'
  | 'Wallets'
  | 'What Pastors Are Saying'
  | 'Who is this offering from?'
  | 'Width'
  | 'You are using this layout'
  | 'You can edit the layout by dragging the fields to the desired position'
  | 'You can restore it any time.'
  | 'Your email address is unverified.'
  | 'Zip Code'
  | 'enum.check_type.payment'
  | 'enum.check_type.refund'
  | 'enum.civil_status.divorced'
  | 'enum.civil_status.married'
  | 'enum.civil_status.separated'
  | 'enum.civil_status.single'
  | 'enum.civil_status.widowed'
  | 'enum.gender.female'
  | 'enum.gender.male'
  | 'enum.language_code.en'
  | 'enum.language_code.es'
  | 'enum.offering_frequency.annually'
  | 'enum.offering_frequency.bi_monthly'
  | 'enum.offering_frequency.bi_weekly'
  | 'enum.offering_frequency.monthly'
  | 'enum.offering_frequency.one_time'
  | 'enum.offering_frequency.quarterly'
  | 'enum.offering_frequency.semi_annually'
  | 'enum.offering_frequency.weekly'
  | 'enum.payment_method.cash'
  | 'enum.payment_method.check'
  | 'enum.tag_type.category'
  | 'enum.tag_type.skill'
  | 'enum.tenant_permission.categories.create'
  | 'enum.tenant_permission.categories.delete'
  | 'enum.tenant_permission.categories.manage'
  | 'enum.tenant_permission.categories.update'
  | 'enum.tenant_permission.check.layouts.create'
  | 'enum.tenant_permission.check.layouts.delete'
  | 'enum.tenant_permission.check.layouts.manage'
  | 'enum.tenant_permission.check.layouts.update'
  | 'enum.tenant_permission.checks.confirm'
  | 'enum.tenant_permission.checks.create'
  | 'enum.tenant_permission.checks.delete'
  | 'enum.tenant_permission.checks.manage'
  | 'enum.tenant_permission.checks.print'
  | 'enum.tenant_permission.checks.update'
  | 'enum.tenant_permission.expense.types.create'
  | 'enum.tenant_permission.expense.types.delete'
  | 'enum.tenant_permission.expense.types.manage'
  | 'enum.tenant_permission.expense.types.update'
  | 'enum.tenant_permission.members.create'
  | 'enum.tenant_permission.members.delete'
  | 'enum.tenant_permission.members.force.delete'
  | 'enum.tenant_permission.members.manage'
  | 'enum.tenant_permission.members.restore'
  | 'enum.tenant_permission.members.update'
  | 'enum.tenant_permission.missionaries.create'
  | 'enum.tenant_permission.missionaries.delete'
  | 'enum.tenant_permission.missionaries.force.delete'
  | 'enum.tenant_permission.missionaries.manage'
  | 'enum.tenant_permission.missionaries.restore'
  | 'enum.tenant_permission.missionaries.update'
  | 'enum.tenant_permission.offering.types.create'
  | 'enum.tenant_permission.offering.types.delete'
  | 'enum.tenant_permission.offering.types.manage'
  | 'enum.tenant_permission.offering.types.update'
  | 'enum.tenant_permission.offerings.create'
  | 'enum.tenant_permission.offerings.delete'
  | 'enum.tenant_permission.offerings.manage'
  | 'enum.tenant_permission.offerings.update'
  | 'enum.tenant_permission.regular.tag.create'
  | 'enum.tenant_permission.regular.tag.delete'
  | 'enum.tenant_permission.regular.tag.update'
  | 'enum.tenant_permission.skills.create'
  | 'enum.tenant_permission.skills.delete'
  | 'enum.tenant_permission.skills.manage'
  | 'enum.tenant_permission.skills.update'
  | 'enum.tenant_permission.users.create'
  | 'enum.tenant_permission.users.delete'
  | 'enum.tenant_permission.users.manage'
  | 'enum.tenant_permission.users.update'
  | 'enum.tenant_permission.wallets.create'
  | 'enum.tenant_permission.wallets.delete'
  | 'enum.tenant_permission.wallets.manage'
  | 'enum.tenant_permission.wallets.update'
  | 'enum.tenant_role.admin'
  | 'enum.tenant_role.no_role'
  | 'enum.tenant_role.secretary'
  | 'enum.tenant_role.super_admin'
  | 'enum.transaction_meta_type.check'
  | 'enum.transaction_meta_type.expense'
  | 'enum.transaction_meta_type.initial'
  | 'enum.transaction_meta_type.offering'
  | 'enum.transaction_type.deposit'
  | 'enum.transaction_type.withdraw'
  | 'enum.wallet_name.primary'
  | '“I love how we can manage both members and missionaries from the same place. It\'s truly built for the church.”';
