export type TranslationKey =
  | ':amount recipient selected|:amount recipients selected'
  | ':count persons'
  | ':model report'
  | ':name follow ups'
  | 'A new verification link has been sent to your email address.'
  | 'A reset link will be sent if the account exists.'
  | 'Accept'
  | 'Access your church data securely from anywhere, on any device, at any time.'
  | 'Account Number'
  | 'Accounting'
  | 'Actions'
  | 'Activate'
  | 'Active'
  | 'Add :model'
  | 'Address'
  | 'Address line 1'
  | 'Address line 2'
  | 'Admin'
  | 'Administration'
  | 'Amount'
  | 'Appearance'
  | 'Appearance Settings'
  | 'Appearance settings'
  | 'Are you sure you want to activate this :model?'
  | 'Are you sure you want to deactivate this :model?'
  | 'Are you sure you want to delete this :model?'
  | "Arrastra y suelta tu foto aquí o haz <span class='filepond--label-action'>clic</span> para seleccionarla"
  | "Arrastra y suelta tus archivos o <span class='filepond--label-action'>Buscar</span>"
  | 'Assigned permissions'
  | 'Attachments'
  | 'Available funds'
  | 'Balance'
  | 'Bank Name'
  | 'Cancel'
  | 'Cash'
  | 'Categories'
  | 'Category'
  | 'Check'
  | 'Check layout'
  | 'Check layout is not available on mobile devices'
  | 'Checks'
  | 'Church'
  | 'Church Name'
  | 'Church Settings'
  | 'Church language'
  | 'ChurchesAdmin gave us peace of mind. Payroll is no longer a burden, and our team finally has time to focus on ministry.”'
  | 'ChurchesAdmin helps you manage your church with ease, while also keeping track of offerings, members and missionaries - all in one beautiful dashboard.'
  | 'ChurchesAdmin. All rights reserved.'
  | 'City'
  | 'Civil status'
  | 'Clergy Payroll Made Easy'
  | 'Click here to resend the verification email.'
  | 'Close'
  | 'Code'
  | 'Codes'
  | 'Columns to show'
  | 'Communication'
  | 'Confirm checks'
  | 'Confirm checks and print'
  | 'Confirm password'
  | 'Confirmed'
  | 'Confirmed Checks'
  | 'Contact Information'
  | 'Contact us: :email | :phone'
  | 'Continue'
  | 'Country'
  | 'Create :model'
  | 'Create a new :model'
  | 'Create layout'
  | 'Current balance'
  | 'Current password'
  | 'Current year'
  | 'Dashboard'
  | 'Date'
  | 'Date of Expense'
  | 'Date of Offering'
  | 'Date of birth'
  | 'Deactivate'
  | 'Default amount'
  | 'Delete'
  | 'Delete :model'
  | 'Description'
  | 'Deseleccionar'
  | 'Donor'
  | 'Edit'
  | 'Edit :model'
  | 'Edit the details of this :model'
  | 'Effortless Church'
  | 'Effortless Church Administration'
  | 'Email'
  | 'Email address'
  | 'Email error if any'
  | 'Emails'
  | 'Ensure your account is using a long, random password to stay secure'
  | 'Enter layout height'
  | 'Enter layout name'
  | 'Enter layout width'
  | 'Enter the value for this field'
  | 'Error message'
  | 'Error submiting the form'
  | 'Every month'
  | 'Every six months'
  | 'Every three months'
  | 'Every two months'
  | 'Every two weeks'
  | 'Every week'
  | 'Every year'
  | 'Expense'
  | 'Expense Details'
  | 'Expense type'
  | 'Expense types'
  | 'Expenses'
  | 'Expenses by month'
  | 'Expenses total'
  | 'First visit'
  | 'First visit date'
  | 'Five Hundred Forty-Nine and 00/100'
  | 'Follow Up'
  | 'Follow Up Notes'
  | 'Follow Ups'
  | 'Follow up date'
  | 'Follow up type'
  | 'Force Delete Member'
  | 'Force Delete Missionary'
  | 'Foto de Perfil'
  | 'From'
  | 'Full name'
  | 'Gender'
  | 'General'
  | 'General information'
  | 'Generate check numbers'
  | 'Global Access'
  | 'Handle housing allowances, tax complexities, and direct deposits - all automated and accurate.'
  | 'Height'
  | 'Here you can update the printing check layout'
  | 'Inactive'
  | 'Initial Amount'
  | 'Initial check number'
  | 'Ir atrás'
  | 'It allows you to set the current year for the application for you to work in.'
  | 'Keep detailed records, contact info, and family ties for every member of your congregation.'
  | 'Language'
  | 'Last Name'
  | 'Last name'
  | "Let us walk you through how ChurchesAdmin can serve your ministry's needs."
  | 'Loading preview'
  | 'Log Out'
  | 'Logo'
  | 'Main'
  | 'Manage :model'
  | 'Manage church information'
  | 'Manage the visits that comes to the church'
  | 'Manage your emails here'
  | 'Manage your profile and account settings'
  | 'Mark this category as regular'
  | 'Mark this skill as regular'
  | 'Member'
  | 'Member Management'
  | 'Members'
  | 'Members email'
  | 'Memo'
  | 'Message'
  | 'Missionaries'
  | 'Missionary'
  | 'Missionary Oversight'
  | 'Name'
  | 'Name of Payee'
  | 'New :model'
  | 'New password'
  | 'No Role'
  | 'No check layout selected for this wallet'
  | 'No data'
  | 'No data available'
  | 'No error message available'
  | 'No notes'
  | 'No options found'
  | 'No results'
  | 'No results found.'
  | 'Not sent yet'
  | 'Note'
  | 'Notes'
  | 'Number'
  | 'Offering'
  | 'Offering Frequency'
  | 'Offering type'
  | 'Offering types'
  | 'Offerings'
  | 'Offerings by month'
  | 'One time only'
  | 'Only admins would be allowed to edit and delete this category'
  | 'Only admins would be allowed to edit and delete this skill'
  | 'Only missionaries with an email address will be shown in the list.'
  | 'Open in new tab'
  | 'Page :index of :total'
  | 'Password'
  | 'Password confirmation'
  | 'Password settings'
  | 'Pastor Maria, Lighthouse Church'
  | 'Payer'
  | 'Payment Method'
  | 'Payment method'
  | 'Persons by month'
  | 'Phone'
  | 'Please use a desktop device to edit the check layout'
  | 'Preview'
  | 'Print checks'
  | 'Profile'
  | 'Profile Settings'
  | 'Profile information'
  | 'Ready to See ChurchesAdmin in Action?'
  | 'Recipient'
  | 'Recipients type'
  | 'Regular tags'
  | 'Reports'
  | 'Required fields'
  | 'Restore Member'
  | 'Restore Missionary'
  | 'Retry sending failed emails'
  | 'Rev. Daniel, Hope Mission Center'
  | 'Role'
  | 'Roles'
  | 'Routing Number'
  | 'Rows per page'
  | 'Save'
  | 'Save password'
  | 'Saved'
  | 'Schedule a demo'
  | 'Search for a country...'
  | 'Secretary'
  | 'Select a group below to compose a new message.'
  | 'Select an option'
  | 'Select the layout you want to use for this wallet or create a new one'
  | 'Select the members you want to send a message to'
  | 'Select the missionaries you want to send a message to'
  | 'Send a message'
  | 'Send a new email to the recipients you selected'
  | 'Send email'
  | 'Send email to members'
  | 'Send email to missionaries'
  | 'Sender'
  | 'Sent at'
  | 'Sent by :name on :date'
  | 'Sent to :name'
  | 'Settings'
  | 'Skill'
  | 'Skills'
  | 'Social Media'
  | 'Some emails failed to send'
  | 'Some recipients have failed to receive the email. Please check their error messages.'
  | 'State'
  | 'Status'
  | 'Subject'
  | 'Summary'
  | 'Super Admin'
  | 'Tags'
  | 'This action cannot be undone'
  | 'This action cannot be undone.'
  | 'This email has no attachments'
  | 'This is how the information will look on the check layout'
  | 'This is marked as regular.'
  | 'This setting is only available for Super Admins.'
  | 'This wallet will be usable again'
  | "This wallet won't be usable until it is activated"
  | 'Timezone'
  | 'Total'
  | 'Track assignments, support levels, communication logs, and prayer requests with ease.'
  | 'Transactions'
  | 'Transfer to member'
  | 'Type'
  | 'Unconfirmed Checks'
  | 'Unknown sender'
  | 'Update :model'
  | "Update account's appearance settings"
  | 'Update password'
  | 'Update the church information'
  | 'Update the website language'
  | 'Update your name and email address'
  | 'Upload the church logo'
  | 'Use this layout'
  | 'User'
  | 'Users'
  | 'Using the :name layout'
  | 'View'
  | 'View email'
  | 'View error'
  | 'View recipients'
  | 'Visit'
  | 'Visitors'
  | 'Visits'
  | 'Wallet'
  | 'Wallet :name'
  | 'Wallets'
  | 'Wallets by month'
  | 'What Pastors Are Saying'
  | 'Who is this offering from?'
  | 'Width'
  | 'You'
  | 'You are using this layout'
  | 'You can edit the layout by dragging the fields to the desired position'
  | 'You can restore it any time.'
  | 'Your email address is unverified.'
  | 'Zip Code'
  | 'datatable.actions'
  | 'datatable.empty'
  | 'datatable.filter'
  | 'datatable.filter_button'
  | 'datatable.hide'
  | 'datatable.no_selected_rows'
  | 'datatable.pagination.first_page'
  | 'datatable.pagination.last_page'
  | 'datatable.pagination.next_page'
  | 'datatable.pagination.page_info'
  | 'datatable.pagination.previous_page'
  | 'datatable.pagination.rows_per_page'
  | 'datatable.pagination.selected_rows'
  | 'datatable.pagination.total_rows'
  | 'datatable.print_button'
  | 'datatable.select.all_pages'
  | 'datatable.select.current_page'
  | 'datatable.select.title'
  | 'datatable.sort.ascending'
  | 'datatable.sort.descending'
  | 'datatable.unselect_filter'
  | 'datatable.visibility_button'
  | 'enum.check_type.payment'
  | 'enum.check_type.refund'
  | 'enum.civil_status.divorced'
  | 'enum.civil_status.married'
  | 'enum.civil_status.separated'
  | 'enum.civil_status.single'
  | 'enum.civil_status.widowed'
  | 'enum.email_status.failed'
  | 'enum.email_status.pending'
  | 'enum.email_status.sending'
  | 'enum.email_status.sent'
  | 'enum.follow_up_type.call'
  | 'enum.follow_up_type.email'
  | 'enum.follow_up_type.in_person'
  | 'enum.follow_up_type.letter'
  | 'enum.gender.female'
  | 'enum.gender.male'
  | 'enum.language_code.en'
  | 'enum.language_code.es'
  | 'enum.model_morph_name.check_layout'
  | 'enum.model_morph_name.church'
  | 'enum.model_morph_name.church_wallet'
  | 'enum.model_morph_name.email'
  | 'enum.model_morph_name.member'
  | 'enum.model_morph_name.missionary'
  | 'enum.model_morph_name.offering_type'
  | 'enum.model_morph_name.user'
  | 'enum.model_morph_name.visit'
  | 'enum.offering_frequency.annually'
  | 'enum.offering_frequency.bi_monthly'
  | 'enum.offering_frequency.bi_weekly'
  | 'enum.offering_frequency.monthly'
  | 'enum.offering_frequency.one_time'
  | 'enum.offering_frequency.quarterly'
  | 'enum.offering_frequency.semi_annually'
  | 'enum.offering_frequency.weekly'
  | 'enum.payment_method.cash'
  | 'enum.payment_method.check'
  | 'enum.tag_type.category'
  | 'enum.tag_type.skill'
  | 'enum.tenant_permission.categories.create'
  | 'enum.tenant_permission.categories.delete'
  | 'enum.tenant_permission.categories.manage'
  | 'enum.tenant_permission.categories.update'
  | 'enum.tenant_permission.check_layouts.create'
  | 'enum.tenant_permission.check_layouts.delete'
  | 'enum.tenant_permission.check_layouts.manage'
  | 'enum.tenant_permission.check_layouts.update'
  | 'enum.tenant_permission.checks.confirm'
  | 'enum.tenant_permission.checks.create'
  | 'enum.tenant_permission.checks.delete'
  | 'enum.tenant_permission.checks.manage'
  | 'enum.tenant_permission.checks.print'
  | 'enum.tenant_permission.checks.update'
  | 'enum.tenant_permission.emails.create'
  | 'enum.tenant_permission.emails.delete'
  | 'enum.tenant_permission.emails.manage'
  | 'enum.tenant_permission.emails.send'
  | 'enum.tenant_permission.emails.send_to.members'
  | 'enum.tenant_permission.emails.send_to.missionaries'
  | 'enum.tenant_permission.emails.update'
  | 'enum.tenant_permission.expense_types.create'
  | 'enum.tenant_permission.expense_types.delete'
  | 'enum.tenant_permission.expense_types.manage'
  | 'enum.tenant_permission.expense_types.update'
  | 'enum.tenant_permission.members.create'
  | 'enum.tenant_permission.members.delete'
  | 'enum.tenant_permission.members.force_delete'
  | 'enum.tenant_permission.members.manage'
  | 'enum.tenant_permission.members.restore'
  | 'enum.tenant_permission.members.update'
  | 'enum.tenant_permission.missionaries.create'
  | 'enum.tenant_permission.missionaries.delete'
  | 'enum.tenant_permission.missionaries.force_delete'
  | 'enum.tenant_permission.missionaries.manage'
  | 'enum.tenant_permission.missionaries.restore'
  | 'enum.tenant_permission.missionaries.update'
  | 'enum.tenant_permission.offering_types.create'
  | 'enum.tenant_permission.offering_types.delete'
  | 'enum.tenant_permission.offering_types.manage'
  | 'enum.tenant_permission.offering_types.update'
  | 'enum.tenant_permission.offerings.create'
  | 'enum.tenant_permission.offerings.delete'
  | 'enum.tenant_permission.offerings.manage'
  | 'enum.tenant_permission.offerings.update'
  | 'enum.tenant_permission.regular_tags.create'
  | 'enum.tenant_permission.regular_tags.delete'
  | 'enum.tenant_permission.regular_tags.update'
  | 'enum.tenant_permission.skills.create'
  | 'enum.tenant_permission.skills.delete'
  | 'enum.tenant_permission.skills.manage'
  | 'enum.tenant_permission.skills.update'
  | 'enum.tenant_permission.users.create'
  | 'enum.tenant_permission.users.delete'
  | 'enum.tenant_permission.users.manage'
  | 'enum.tenant_permission.users.update'
  | 'enum.tenant_permission.visits.create'
  | 'enum.tenant_permission.visits.delete'
  | 'enum.tenant_permission.visits.force_delete'
  | 'enum.tenant_permission.visits.manage'
  | 'enum.tenant_permission.visits.restore'
  | 'enum.tenant_permission.visits.update'
  | 'enum.tenant_permission.wallets.check_layout.update'
  | 'enum.tenant_permission.wallets.create'
  | 'enum.tenant_permission.wallets.delete'
  | 'enum.tenant_permission.wallets.manage'
  | 'enum.tenant_permission.wallets.update'
  | 'enum.tenant_role.admin'
  | 'enum.tenant_role.no_role'
  | 'enum.tenant_role.secretary'
  | 'enum.tenant_role.super_admin'
  | 'enum.transaction_meta_type.check'
  | 'enum.transaction_meta_type.expense'
  | 'enum.transaction_meta_type.initial'
  | 'enum.transaction_meta_type.offering'
  | 'enum.transaction_type.deposit'
  | 'enum.transaction_type.previous_balance'
  | 'enum.transaction_type.withdraw'
  | 'enum.wallet_name.primary'
  | 'file_uploader.file_size.exceeded'
  | 'file_uploader.file_size.title'
  | 'file_uploader.file_size.total.exceeded'
  | 'file_uploader.file_size.total.title'
  | 'file_uploader.file_type.allowed'
  | 'file_uploader.file_type.not_allowed'
  | 'file_uploader.idle'
  | "“I love how we can manage both members and missionaries from the same place. It's truly built for the church.”";
