export enum UserPermission {
    UPDATE_REGULAR_TAG = 'update_regular_tag',
    DELETE_REGULAR_TAG = 'delete_regular_tag',
    CREATE_USERS = 'create_users',
    UPDATE_USERS = 'update_users',
    DELETE_USERS = 'delete_users',
    CREATE_SKILLS = 'create_skills',
    UPDATE_SKILLS = 'update_skills',
    DELETE_SKILLS = 'delete_skills',
    CREATE_CATEGORIES = 'create_categories',
    UPDATE_CATEGORIES = 'update_categories',
    DELETE_CATEGORIES = 'delete_categories',
    CREATE_MEMBERS = 'create_members',
    UPDATE_MEMBERS = 'update_members',
    DELETE_MEMBERS = 'delete_members',
    CREATE_MISSIONARIES = 'create_missionaries',
    UPDATE_MISSIONARIES = 'update_missionaries',
    DELETE_MISSIONARIES = 'delete_missionaries',
}
