export enum UserPermission {
  UPDATE_REGULAR_TAG = 'regular_tag_update',
  DELETE_REGULAR_TAG = 'regular_tag_delete',
  CREATE_REGULAR_TAG = 'regular_tag_create',
  MANAGE_USERS = 'users_manage',
  CREATE_USERS = 'users_create',
  UPDATE_USERS = 'users_update',
  DELETE_USERS = 'users_delete',
  MANAGE_SKILLS = 'skills_manage',
  CREATE_SKILLS = 'skills_create',
  UPDATE_SKILLS = 'skills_update',
  DELETE_SKILLS = 'skills_delete',
  MANAGE_CATEGORIES = 'categories_manage',
  CREATE_CATEGORIES = 'categories_create',
  UPDATE_CATEGORIES = 'categories_update',
  DELETE_CATEGORIES = 'categories_delete',
  MANAGE_MEMBERS = 'members_manage',
  CREATE_MEMBERS = 'members_create',
  UPDATE_MEMBERS = 'members_update',
  DELETE_MEMBERS = 'members_delete',
  FORCE_DELETE_MEMBERS = 'members_force_delete',
  RESTORE_MEMBERS = 'members_restore',
  MANAGE_MISSIONARIES = 'missionaries_manage',
  CREATE_MISSIONARIES = 'missionaries_create',
  UPDATE_MISSIONARIES = 'missionaries_update',
  DELETE_MISSIONARIES = 'missionaries_delete',
  FORCE_DELETE_MISSIONARIES = 'missionaries_force_delete',
  RESTORE_MISSIONARIES = 'missionaries_restore',
}
export enum UserRole {
  SUPER_ADMIN = 'super_admin',
  ADMIN = 'admin',
  SECRETARY = 'secretary',
  NO_ROLE = 'no_role',
}
